src/js/components/navigationFrame/connectedNavigationFrame.js, src/js/components/navigationFrame/navigationFrame.jsx, src/js/components/navigationFrame/subComponents/navigationBar.jsx
=> Users name is now shown in navigation bar when logged in.

src/js/lib/api/mock.js
=> JSON mock object added to mock.js (getUserInfo)

src/js/app.jsx, src/js/components/navigationFrame/navigationFrame.jsx, src/js/components/views/submissionView/connectedSubmissionView.js, src/js/components/views/submissionView/submissionView.jsx
Closes https://github.com/tair/toastdos-front/issues/10
=> Navigate to submission

src/js/modules/authentication/actions.js
https://github.com/tair/toastdos-front/issues/7
=> bug 7 fix: safari incognito

src/js/modules/authentication/actions.js
Fix for issue #7 (Login doesn't work with Safari incognito mode)
=> Bug Fix 7: updated line 45 with try/catch statement

src/css/buttons.scss, src/css/customSelect.scss, src/css/customTextArea.scss, src/css/customTextInput.scss, src/css/globals.scss, src/css/main.scss, src/css/submissionView.scss, src/js/lib/components/customSelect.jsx, src/js/lib/components/customTextArea.jsx, src/js/lib/components/customTextInput.jsx, src/js/modules/submission/components/annotationList/annotationList.jsx, src/js/modules/submission/components/annotationList/index.js, src/js/modules/submission/components/annotationList/subcomponents/annotationEntry/annotationEntry.jsx, src/js/modules/submission/components/annotationList/subcomponents/annotationFormats/comment.jsx, src/js/modules/submission/components/annotationList/subcomponents/annotationFormats/geneGene.jsx, src/js/modules/submission/components/annotationList/subcomponents/annotationFormats/geneTerm.jsx, src/js/modules/submission/components/annotationList/subcomponents/genePicker/genePicker.jsx, src/js/modules/submission/components/geneList/geneList.jsx, src/js/modules/submission/components/geneList/subcomponents/singleGene/singleGene.jsx, src/js/modules/submission/components/publicationField/publicationField.jsx, src/js/modules/submission/components/submissionView/submissionView.jsx, src/js/modules/submission/reducer.js, src/js/modules/submission/selectors.js
Initial styles for site and layouts for submission UI components are completed.
=> Initial styles

package.json, src/js/app.jsx, src/js/lib/components/authentication/connectedAuthentication.js, src/js/lib/routeChecks.js, src/js/modules/authentication/actions.js, src/js/modules/authentication/components/TokenWatchdog/TokenWatchdog.js, src/js/modules/authentication/components/TokenWatchdog/index.js, src/js/modules/authentication/components/loginView/index.js, src/js/modules/authentication/index.js, src/js/modules/authentication/reducer.js, src/js/modules/authentication/selectors.js, src/js/modules/navigation/components/navigationFrame/index.js, src/js/modules/submission/components/annotationList/annotationList.jsx
=> Expired tokens

src/js/modules/submission/components/annotationList/subcomponents/annotationFormats/comment.jsx, src/js/modules/submission/components/annotationList/subcomponents/annotationFormats/geneGene.jsx, src/js/modules/submission/components/annotationList/subcomponents/annotationFormats/geneTerm.jsx, src/js/modules/submission/components/geneList/subcomponents/singleGene/singleGene.jsx, src/js/modules/submission/components/publicationField/publicationField.jsx, src/js/modules/submission/components/submissionReadOnly/submissionReadOnly.jsx
To be consistent with the rest of the application.
=> Update GeneGene and Comment annotations' UI

src/js/lib/components/smartTextInput/smartTextInput.jsx, src/js/modules/submission/components/annotationList/subcomponents/annotationFormats/comment.jsx, src/js/modules/submission/components/annotationList/subcomponents/annotationFormats/geneGene.jsx, src/js/modules/submission/components/annotationList/subcomponents/annotationFormats/geneTerm.jsx, src/js/modules/submission/components/geneList/subcomponents/singleGene/singleGene.jsx, src/js/modules/submission/components/labelInputRow/index.js, src/js/modules/submission/components/labelInputRow/labelInputRow.jsx, src/js/modules/submission/components/publicationField/publicationField.jsx, src/js/modules/submission/selectors.js
- Fix Issues #49 and #50 
- Create a LabelInputRow component to reduce code repetition
=> Fixes and cleanup

src/js/modules/submission/components/annotationList/annotationList.jsx, src/js/modules/submission/components/annotationList/subcomponents/annotationFormats/geneTerm.jsx
Needs to be changed to a reducer method later.
=> When changing Method, evidenceWith codes reset

src/js/lib/components/smartTextInput/smartTextInput.jsx, src/js/lib/components/smartTextInput/subcomponents/suggestionList.jsx, src/js/modules/submission/components/annotationList/annotationList.jsx, src/js/modules/submission/components/annotationList/subcomponents/annotationFormats/comment.jsx, src/js/modules/submission/components/annotationList/subcomponents/annotationFormats/geneGene.jsx, src/js/modules/submission/components/annotationList/subcomponents/annotationFormats/geneTerm.jsx, src/js/modules/submission/components/geneList/geneList.jsx, src/js/modules/submission/components/geneList/subcomponents/singleGene/singleGene.jsx, src/js/modules/submission/components/keywordTextInput/keywordTextInput.jsx, src/js/modules/submission/components/publicationField/publicationField.jsx, src/js/modules/submission/components/submissionReadOnly/submissionReadOnly.jsx, src/js/modules/submission/reducer.js, src/js/modules/submission/selectors.js
Improve submission process based on user feedback.
=> Submission clarification

src/js/modules/submission/actionTypes.js, src/js/modules/submission/actions.js, src/js/modules/submission/components/geneList/geneList.jsx, src/js/modules/submission/components/geneList/index.js, src/js/modules/submission/reducer.js
Merge commit that has ClearGene working with store, but not state.
=> Method remove action

src/js/modules/curation/components/curationDetailView/curationDetailView.jsx, src/js/modules/home/components/homeView/homeView.jsx, src/js/modules/submission/actions.js, src/js/modules/submission/components/annotationList/annotationList.jsx, src/js/modules/submission/components/annotationList/index.js, src/js/modules/submission/components/annotationList/subcomponents/annotationEntry/annotationEntry.jsx, src/js/modules/submission/components/geneList/geneList.jsx, src/js/modules/submission/components/geneList/index.js, src/js/modules/submission/components/publicationField/index.js, src/js/modules/submission/components/publicationField/publicationField.jsx, src/js/modules/submission/components/submissionReadOnly/index.js, src/js/modules/submission/components/submissionReadOnly/submissionReadOnly.jsx, src/js/modules/submission/components/submissionView/index.js, src/js/modules/submission/components/submissionView/submissionView.jsx, src/js/modules/submission/reducer.js, src/js/modules/submission/selectors.js
Refactoring submission to better support curation.
- Update GOAT name
- store and reducer cleanup
=> Curation refactoring

src/js/domain/annotation/actionTypes.js, src/js/domain/annotation/actions.js, src/js/domain/annotation/constants.js, src/js/domain/annotation/reducer.js, src/js/lib/api/real.js, src/js/modules/connectedComponents/annotation/entry.js, src/js/modules/connectedComponents/annotation/list.js, src/js/modules/connectedComponents/gene/list.js, src/js/modules/connectedComponents/submissionView.js, src/js/modules/curationDetail/actionTypes.js, src/js/modules/curationDetail/actions.js, src/js/modules/curationDetail/reducer.js, src/js/modules/curationDetail/selectors.js, src/js/modules/submission/reducer.js, src/js/modules/submission/selectors.js, src/js/ui/annotation/entry.jsx, src/js/ui/annotation/statusButton.jsx, src/js/ui/curation/footer.jsx, src/js/ui/curation/view.jsx, src/js/ui/gene/list.jsx, src/js/ui/submission/viewReadOnly.jsx
=> Curation connection

src/js/domain/annotation/selectors.js, src/js/modules/connectedComponents/curationView.js, src/js/modules/curationDetail/selectors.js, src/js/ui/curation/footer.jsx, src/js/ui/curation/view.jsx, src/js/ui/curationOverviewView.jsx
- Finish curating button
- Update curation overview title
=> Minor ui updates

.gitignore, src/js/lib/components/smartTextInput/subcomponents/suggestionList.jsx
=> Display external id in keyword search

src/js/ui/externalIdBadge.jsx
=> Add PO and ECO external links #251

.travis.yml
=> Update localdir in travis yml

.travis.yml, appspec.yml, server-scripts/after-install
=> Add CodeDeploy support

.travis.yml
tair/toastdos-back#248
Test S3 deployment changes.
=> Fix before_deploy for travis

.travis.yml
=> Modify upload-dir in travis.yml

.travis.yml
=> Add codedeploy deployment to travis

scripts/generateOrcidFile.js
=> Use orcid auth url in env variable

appspec.yml, server-scripts/after-install
Testing front deployment to new landing dir.
tair/toastdos-back#248
=> Move codedeploy landing dir

appspec.yml
=> Update serverscript to run as ec2-user

src/js/modules/submission/selectors.js
=> Fix lint issue

src/js/ui/exportsView.jsx
=> Moved readme onto page and did some formatting

src/js/lib/components/customTextInput.jsx, src/js/modules/userInfo/components/addEmailPanel/addEmailPanel.jsx, src/js/modules/userInfo/components/addEmailPanel/index.js, src/js/modules/userInfo/index.js, src/js/ui/adminView.jsx, src/js/ui/submission/viewReadOnly.jsx
=> Adds email updating to the submission review page

src/js/domain/annotation/selectors.js, src/js/modules/connectedComponents/annotation/geneGene.js, src/js/modules/connectedComponents/annotation/geneTerm.js, src/js/ui/annotation/entry.jsx
=> Fix curation validation when accepted

src/js/domain/annotation/selectors.js, src/js/modules/connectedComponents/curationView.js, src/js/modules/curationDetail/selectors.js, src/js/ui/curation/view.jsx, src/js/ui/curation/viewReadOnly.jsx, src/js/ui/validationInput.jsx
=> Make viewing a reviewed submission readonly
